### ISSUE TITLE
Installation issue on Windwos 10

### ISSUE THREAD

**Issue by abdulmateenraj** [IHTSDO/snap2snomed#164]
Hi,

I encountered the following issue when tried to install Snap2Snomed on a Windows 10 machine. It seems the command "rm -rf dist TESTS*" is not found and I tried to install Rimraf package as suggested [here ](https://stackoverflow.com/questions/40682848/how-to-clean-delete-contents-folder-with-npm)but the issue remained unchanged. Any idea ?
![SNAP2SnomedCT_Error2 (1)](https://user-images.githubusercontent.com/13238338/234916067-5bad95bd-fe94-47e8-ac52-aada99f99000.JPG)

```
[INFO] --- frontend:1.12.1:yarn (yarn clean) @ ui ---
[INFO] Running 'yarn run clean' in C:\Temp\snap2snomed-main\ui\snapclient
[INFO] yarn run v1.22.10
[INFO] $ rm -rf dist TESTS*
[INFO] Der Befehl "rm" ist entweder falsch geschrieben oder
[INFO] konnte nicht gefunden werden.
[INFO] error Command failed with exit code 1.
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SNAP-2-SNOMED 0.1.0-SNAPSHOT:
[INFO]
[INFO] SNAP-2-SNOMED ...................................... SUCCESS [  0.745 s]
[INFO] Snap2SNOMED API .................................... SUCCESS [04:32 min]
[INFO] SNAP-2-SNOMED UI ................................... FAILURE [  3.295 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:37 min
[INFO] Finished at: 2023-04-27T17:39:31+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:yarn (yarn clean) on project ui: Failed to run task: 'yarn run clean' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ui
```

**Comment by kaicode** [comment]
It looks like the yarn step failed because the `rm` command is not available. Running the build in PowerShell should solve this problem, see https://stackoverflow.com/a/97896

**Comment by abdulmateenraj** [comment]
With PowerShell, the process doesn't go beyond this step. I Pulled "https://registry-1.docker.io/v2/aehrc/jre/manifests/openjdk-11-fontconfig" manually but that didn't solve this issue.


![image](https://github.com/IHTSDO/snap2snomed/assets/13238338/65c77b34-2db3-4d31-b7b2-14871c326294)
